apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tesla-sync.fullname" . }}
  labels:
    {{- include "tesla-sync.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tesla-sync.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tesla-sync.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "tesla-sync.fullname" . }}-config
            - secretRef:
                name: {{ include "tesla-sync.fullname" . }}-db-secrets
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: logs
              mountPath: /app/logs
          {{- end }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: {{ include "tesla-sync.fullname" . }}-logs
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
