apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "tesla-sync.fullname" . }}
  labels:
    {{- include "tesla-sync.labels" . | nindent 4 }}
  annotations:
    # Optional: Ensure job can be rerun
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 3  # Number of retries before marking job as failed
  activeDeadlineSeconds: 3600  # Maximum time the job can run
  template:
    metadata:
      labels:
        {{- include "tesla-sync.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "tesla-sync.fullname" . }}-config
            - secretRef:
                name: {{ include "tesla-sync.fullname" . }}-db-secrets
          
          # Optional: Resource constraints
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      # Optional: Node selection
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
