apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tesla-sync.fullname" . }}-db-secrets
  labels:
    {{- include "tesla-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  TESLALOGGER_DB_PASSWORD: {{ .Values.secrets.teslaloggerDbPassword | quote }}
  TESLAMATE_DB_PASSWORD: {{ .Values.secrets.teslamateDbPassword | quote }}
